export default [
	{
		index: 0,
		name: "Andy",
		age: 5,
		breed: "Labrador Retriever",
		location: "Wiltshire, England",
		alt: "Andy, a black Labrador, smiles brightly.",
		doginalities: [
			"Shy and quiet",
			"Easy to train",
			"Crazy about food",
			"Very smart",
			"Pro fetch player",
			"Loves cuddles",
		],
	},
	{
		index: 1,
		name: "Aki",
		age: 3,
		breed: "Shiba Inu",
		location: "Cambridgeshire, England",
		alt: "Aki, a brown Shiba Inu, looks up and smiles.",
		doginalities: [
			"Independent",
			"Adventurous and fun-loving",
			"likes human company",
			"Strong-willed",
			"Treasures good hygiene",
			"Good with children",
		],
	},
	{
		index: 2,
		name: "Sophie",
		age: 8,
		breed: "Samoyed",
		location: "London, England",
		alt: "Sophie, a Samoyed, is resting on the floor.",
		doginalities: [
			"Super fluffy",
			"Good-natured",
			"Can live with other pets",
			"Loves toys and games",
			"Always on the go",
			"Pro fetch player",
		],
	},
	{
		index: 3,
		name: "Albert",
		age: 5,
		breed: "Siberian Husky",
		location: "Flintshire, Wales",
		alt: "Albert, a Siberian Husky, is patted on the head.",
		doginalities: [
			"Outgoing and friendly",
			"Howling master",
			"Good with children",
			"Doesn't like cats",
			"Slow learner",
			"Energetic",
		],
	},
	{
		index: 4,
		name: "Caramel",
		age: 10,
		breed: "Golden Retriever",
		location: "Edinburgh, Scotland",
		alt: "Caramel, a Golden Retriever, smiles while looking away.",
		doginalities: [
			"Quiet but loving",
			"Slow walker",
			"Difficulty seeing",
			"Super fluffy",
			"Can be at home alone",
			"Well-behaved",
		],
	},
	{
		index: 5,
		name: "Max",
		age: 1,
		breed: "Golden Retriever",
		location: "Tyrone, Northern Ireland",
		alt: "Max, a Golden Retriever, runs towards the camera.",
		doginalities: [
			"Loves toys and games",
			"Brave and curious",
			"Good with children",
			"Needs training",
			"Can't be home alone",
			"Super smart",
		],
	},
	{
		index: 6,
		name: "Udon",
		age: 1,
		breed: "Bichon Frise",
		location: "Ayrshire, Scotland",
		alt: "Udon, a Bichon Frise, lies on a meadow.",
		doginalities: [
			"Shy and introverted",
			"Loves nature",
			"Always on the go",
			"Crazy about food",
			"Loves cuddles",
			"Can live with other pets",
		],
	},
	{
		index: 7,
		name: "Kay",
		age: 2,
		breed: "Beagle",
		location: "Yorkshire, England",
		alt: "Kay, a Beagle, lies on a meadow.",
		doginalities: [
			"Howling master",
			"Playful",
			"Gentle and sweet",
			"Good with children",
			"Energetic",
			"Easy to train",
		],
	},
	{
		index: 8,
		name: "Laurel",
		age: 11,
		breed: "Chow Chow",
		location: "Pembrokeshire, Wales",
		alt: "Laurel, a Chow Chow, stands on a meadow handsomely.",
		doginalities: [
			"Loyal",
			"Good guard dog",
			"Aloof with strangers",
			"Can't live with other dogs",
			"Fiercely protective",
			"Super super super fluffy",
		],
	},
	{
		index: 9,
		name: "Anna",
		age: 1,
		breed: "German Shepherd",
		location: "Fermanagh, Northern Ireland",
		alt: "Anna, a German Shepherd puppy with beaming eyes.",
		doginalities: [
			"Good with children",
			"Alert and watchful",
			"Reserved and quiet",
			"Loyal",
			"Easy-going and approachable",
			"Strong and protective",
		],
	},
	{
		index: 10,
		name: "Victor",
		age: 12,
		breed: "Labrador Retriever",
		location: "Essex, England",
		alt: "Victor, a brown Labrador, looks at the camera gently.",
		doginalities: [
			"Easy to train",
			"Energetic and active",
			"Howling master",
			"Outgoing and friendly",
			"Thrive on activity",
			"Eager to please",
		],
	},
	{
		index: 11,
		name: "Doug",
		age: 3,
		breed: "Pug",
		location: "Aberdeenshire, Scotland",
		alt: "Doug, a Pug on a leash, smiles brightly.",
		doginalities: [
			"Affectionate and loving",
			"Playful and active",
			"Can live with other animals",
			"Shed a lot",
			"Needs training",
			"Craves attention",
		],
	},
	{
		index: 12,
		name: "Brandon",
		age: 2,
		breed: "Pembroke Welsh Corgi",
		location: "Manchester, England",
		alt: "Brandon, a Pembroke Welsh Corgi, stands on a meadow.",
		doginalities: [
			"Happy and cheerful",
			"Good with children",
			"Easy to train",
			"Crazy about food",
			"Independent and strong-willed",
			"Very smart",
		],
	},
	{
		index: 13,
		name: "Mia",
		age: 4,
		breed: "Toy Poodle",
		location: "Clwyd, Wales",
		alt: "Mia, a Toy Poodle, runs towards the camera happily.",
		doginalities: [
			"Super fluffy",
			"Athletic and agile",
			"No shedding at all",
			"Lively and playful",
			"Sensitive to loud voices",
			"Loves barking",
		],
	},
	{
		index: 14,
		name: "Iona",
		age: 6,
		breed: "Alaskan Malamute",
		location: "Oxfordshire, England",
		alt: "Iona, a An Alaskan Malamute, smiles happily.",
		doginalities: [
			"Cheerful and outgoing",
			"Strong willed and independent",
			"Loyal",
			"Super fluffy",
			"Thrive on activity",
			"Howling master",
		],
	},
];
